[package]
name = "renderust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
minifb = "0.28.0"
rand = "0.8.5"
num = "0.4.0"
image = "0.23.12"
glam = "0.21.3"
derive_builder = "0.11.2"