[package]
name = "renderust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
minifb = "0.23"
rand = "0.8.5"
thiserror = "1.0.32"
num = "0.4.0"
image = "0.18.0"
nalgebra = "0.30.1"